# Generated by Django 6.0.4 on 2026-04-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bookings', models.IntegerField()),
                ('avg_fee', models.FloatField()),
                ('commission_rate', models.FloatField()),
                ('experience_years', models.IntegerField()),
                ('rating_avg', models.FloatField()),
                ('district', models.CharField(max_length=100)),
                ('specialization_group', models.CharField(max_length=100)),
                ('hospital_type', models.CharField(max_length=100)),
                ('lag_1', models.FloatField()),
                ('lag_7', models.FloatField()),
                ('rolling_mean_7', models.FloatField()),
                ('prediction', models.FloatField(blank=True, null=True)),
                ('forecast_days', models.IntegerField(default=30)),
                ('forecast_total', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Forecast Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
